import { Injectable } from "@angular/core";
import { Modello } from "./modello.model";

@Injectable()
export class ElencoModelliService {
  // elenco di tutti i modelli e delle relative caratteristiche
  elenco: Modello[] = [
    {
      id: "Audi a1",
      cv: " disponibile da 95 a 150 cavalli",
      peso: "un peso di 1.165 kg",
      prezzo: "a partire da 22.500,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a1.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a1/a1-sportback.html",
      accelerazione: "da 6,5 a 11,5 secondi",
     },
     {
      id: "Audi a3",
      cv: " disponibile da 110 a 150 cavalli",
      peso: "un peso di 1.210 kg",
      prezzo: "a partire da 29.600,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20s3.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a3/a3-sportback.html",
      accelerazione: "da 6,8 a 10,6 secondi",
     },
     {
      id: "Audi a4",
      cv: " disponibile da 150 a 286 cavalli",
      peso: "un peso di 1.320 kg",
      prezzo: "a partire da 42.600,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a4.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a4/a4-avant.html",
      accelerazione: "da 5,2 a 9,8 secondi",
     },
     {
      id: "Audi a5",
      cv: " disponibile da 204 a 286 cavalli",
      peso: "un peso di 1.590 kg",
      prezzo: "a partire da 48.100,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a5.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a5/a5_sportback.html",
      accelerazione: "da 5,1 a 8,7 secondi" ,
     },
     {
      id: "Audi a6",
      cv: " disponibile da 163 a 340 cavalli",
      peso: "un peso di 1745 kg",
      prezzo: "a partire da 54.920,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a6.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a6/a6-avant.html",
      accelerazione: "da 5,3 a 9,3 secondi",
     },
     {
      id: "Audi a7",
      cv: " disponibile da 204 a 340 cavalli",
      peso: "un peso di 1.815 kg",
      prezzo: "a partire da 63.500,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a7.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a7/a7-sportback.html",
      accelerazione: "da 5,3 a 8,3 secondi",
     },
     {
      id: "Audi q2",
      cv: " disponibile da 110 a 150 cavalli",
      peso: "un peso di 1.325 kg",
      prezzo: "a partire da 28.400,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q2.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/q2/nuova-q2.html",
      accelerazione: "da 6,7 a 11,2 secondi",
     },
     {
      id: "Audi a8",
      cv: " disponibile da 286 a 460 cavalli",
      peso: "un peso di 2.165 kg",
      prezzo: "a partire da 105.050,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a8.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/a8/a8.html",
      accelerazione: "da 4,4 a 5,9 secondi",
     },
     {
      id: "Audi q3",
      cv: " disponibile da 150 a 245 cavalli",
      peso: "un peso di 1.810 kg",
      prezzo: "a partire da 36.150,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q3.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/q3/q3.html",
      accelerazione: "da 5,8 a 9,5 secondi",
     },
     {
      id: "Audi q5",
      cv: " disponibile da 163 a 286 cavalli",
      peso: "un peso di 1.165 kg",
      prezzo: "a partire da 51.250,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q5.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/q5/nuova-q5.html",
      accelerazione: "da 5,3 a 9 secondi",
     },
     {
      id: "Audi q7",
      cv: " disponibile da 231  a 340 cavalli",
      peso: "un peso di 2.130 kg",
      prezzo: "a partire da 72.450,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q7.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/q7/q7.html",
      accelerazione: "da 5,4 a 7,3 secondi",
     },
     {
      id: "Audi q8",
      cv: " disponibile da 231  a 340 cavalli",
      peso: "un peso di 2.175 kg",
      prezzo: "a partire da 77.600,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q8.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/q8.html",
      accelerazione: "da 5,4 a 7,1 secondi",
     },
     {
      id: "Audi TT",
      cv: " disponibile solo con 245 cavalli",
      peso: "un peso di 1.370 kg",
      prezzo: "a partire da 47.860,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20tt.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/tt/tt-coupe.html",
      accelerazione: "da 5,1 a 6,9 secondi",
     },
     {
      id: "Audi e-tron",
      cv: " disponibile solo con 600 cavalli",
      peso: "un peso di 2.420 kg",
      prezzo: "a partire da 147.800,00 €",
      motore: "elettrico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20e-tron.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/e-tron-gt/audi-rs-e-tron-gt.html",
      accelerazione: "da 4,5 a 6,8 secondi",
     },
     {
      id: "Audi r8",
      cv: " disponibile da 540 a 620 CV",
      peso: "un peso di 1.670 kg",
      prezzo: "a partire da 155.988,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20r8.jpg?raw=true",
      configura: "https://www.audi.it/it/web/it/modelli/r8/r8-coupe-v10-rwd.html",
      accelerazione: "da 3,1 a 3,8 secondi",
     },
  ];
  constructor() {}
}
