import { Injectable } from "@angular/core";
import { Modello } from "./modello.model";

@Injectable()
export class ElencoModelliService {
  elenco: Modello[] = [
    {
      id: "Audi a1",
      cv: " disponibile da 95 a 150 cavalli",
      peso: "un peso di 1.165 kg",
      prezzo: "a partire da 22.500,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a1.jpg?raw=true",
     },
     {
      id: "Audi a3",
      cv: " disponibile da 110 a 150 cavalli",
      peso: "un peso di 1.210 kg",
      prezzo: "a partire da 29.600,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20s3.jpg?raw=true",
     },
     {
      id: "Audi a4",
      cv: " disponibile da 150 a 286 cavalli",
      peso: "un peso di 1.320 kg",
      prezzo: "a partire da 42.600,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a4.jpg?raw=true",
     },
     {
      id: "Audi a5",
      cv: " disponibile da 204 a 286 cavalli",
      peso: "un peso di 1.590 kg",
      prezzo: "a partire da 48.100,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a5.jpg?raw=true",
     },
     {
      id: "Audi a6",
      cv: " disponibile da 163 a 340 cavalli",
      peso: "un peso di 1745 kg",
      prezzo: "a partire da 54.920,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a6.jpg?raw=true",
     },
     {
      id: "Audi a7",
      cv: " disponibile da 204 a 340 cavalli",
      peso: "un peso di 1.815 kg",
      prezzo: "a partire da 63.500,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a7.jpg?raw=true",
     },
     {
      id: "Audi q2",
      cv: " disponibile da 110 a 150 cavalli",
      peso: "un peso di 1.325 kg",
      prezzo: "a partire da 28.400,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q2.jpg?raw=true",
     },
     {
      id: "Audi a8",
      cv: " disponibile da 286 a 460 cavalli",
      peso: "un peso di 2.165 kg",
      prezzo: "a partire da 105.050,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20a8.jpg?raw=true",
     },
     {
      id: "Audi q3",
      cv: " disponibile da 150 a 245 cavalli",
      peso: "un peso di 1.810 kg",
      prezzo: "a partire da 36.150,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q3.jpg?raw=true",
     },
     {
      id: "Audi q5",
      cv: " disponibile da 163 a 286 cavalli",
      peso: "un peso di 1.165 kg",
      prezzo: "a partire da 51.250,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q5.jpg?raw=true",
     },
     {
      id: "Audi q7",
      cv: " disponibile da 231  a 340 cavalli",
      peso: "un peso di 2.130 kg",
      prezzo: "a partire da 72.450,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q7.jpg?raw=true",
     },
     {
      id: "Audi q8",
      cv: " disponibile da 231  a 340 cavalli",
      peso: "un peso di 2.175 kg",
      prezzo: "a partire da 77.600,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20q8.jpg?raw=true",
     },
     {
      id: "Audi TT",
      cv: " disponibile solo con 245 cavalli",
      peso: "un peso di 1.370 kg",
      prezzo: "a partire da 47.860,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20tt.jpg?raw=true",
     },
     {
      id: "Audi e-tron",
      cv: " disponibile solo con 600 cavalli",
      peso: "un peso di 2.420 kg",
      prezzo: "a partire da 147.800,00 €",
      motore: "elettrico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20e-tron.jpg?raw=true",
     },
     {
      id: "Audi r8",
      cv: " disponibile da 540 a 620 CV",
      peso: "un peso di 1.670 kg",
      prezzo: "a partire da 155.988,00 €",
      motore: "termico",
      img: "https://github.com/MatioliSimone/copertinaIMG/blob/main/copertinaIMG-main/Audi%20r8.jpg?raw=true",
     },
  ];
  constructor() {}
}
